### ISSUE TITLE
Swate installed but not shown in the Add-ins list

### ISSUE THREAD

**Issue by fathoni** [omaus/Swate_Install#1]
Following the [Swate Installer](https://github.com/omaus/Swate_Install) documentation, the installation process seems to be successfully completed as shown in the screenshot below:

<img width="674" alt="2021-07-08 10_38" src="https://user-images.githubusercontent.com/1597027/124891678-80fe9f80-dfd9-11eb-8c46-a2e7d94584d3.png">

However, it is not shown in the Excel add-ins list:

<img width="569" alt="2021-07-08 10_46_20-" src="https://user-images.githubusercontent.com/1597027/124892063-d175fd00-dfd9-11eb-9253-a4d975e5e451.png">

In this case, Excel for Microsoft 365 version 2106 Build 14131.20278 was used on Windows 10. Both Excel and Windows have been restarted. 

Are there any extra steps that should be carefully followed to solve this issue? 

Thank you in advance.

EDIT: just found that a similar issue has been posted [here](https://github.com/nfdi4plants/Swate/issues/148), and the online installation works fine.

**Comment by omaus** [comment]
Just to make sure what's the problem: Did you click on the little arrow next to _My Add-ins_ or on _My Add-ins_ itself? :sweat_smile:

![image](https://user-images.githubusercontent.com/47781170/124938405-8aebc700-e008-11eb-8753-b55d55737553.png)

Because to start Swate, you have to click on the little arrow.
It's normal that it doesn't appear in the Excel add-ins and it probably won't until it can be downloaded via Office's Add-in store.

**Comment by fathoni** [comment]
Ah, my bad, indeed I did not click the arrow but in the _My add-ins_ itself, sorry for the confusion! 😅
